### ISSUE TITLE
Responder mode not possible

### ISSUE THREAD

**Issue by hjwe** [Plinzen/android-rttmanager-compat#3]
Hi

I get the following stacktrace after trying to set a phone (google 5x) in responder mode.
 
Caused by: java.lang.IllegalArgumentException: android.net.wifi.RttManager$ResponderCallback is not an interface      
at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:426)                                                                                                  at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:741)                                                                                                  at de.plinzen.rttmanager.RttManagerCompatUtil.wrapResponderCallback(RttManagerCompatUtil.java:120)                                                                                                  at de.plinzen.rttmanager.RttManagerCompat.enableResponder(RttManagerCompat.java:988)

After some googling seems like the Proxy framework only works on interfaces and not abstract classes (ResponderCallback). Does this match your experience, i.e. responder mode in not possible to enable. 
I don't have a AP with 802.11mc features, and doesn't seem like you can buy one either (yet).

**Comment by Plinzen** [comment]
I will have a look on it. To be honest, I just wrapped this method, but I never used it in my samples. I just used startRanging and stopRanging method in RttManagerCompat. 
We have a draft router from Intel with Galileo chipset. I am not sure, if it is possible to get such one officially.

**Comment by Plinzen** [comment]
It is currently not possible to use the `enableResponder` and `disableResponder` methods. The methods take the class `ResponderCallback` as parameter, which is a abstract class and not an interface. It is not possible to proxy an abstract class with Java's `Proxy` feature.
